dist: xenial    # Ubuntu 16.04

sudo: required  # Virtual machine

language: cpp   # C++ enviroment

os:
  - linux       # Only Linux for now

compiler:
  - clang
  - gcc

env:
  - QT=57 PPA=beineri/opt-qt571-xenial

before_install:
  - sudo add-apt-repository -y ppa:$PPA    # Add Qt repo
  - sudo apt-get -qy update                # Update repo

install:
  - sudo apt-get -qy install qt${QT}base qt${QT}multimedia libgl1-mesa-dev   # install specific Qt version

before_script:
  - '"$CXX" != clang++ || export QMAKESPEC=linux-clang'
  - '"$CXX" != g++     || export QMAKESPEC=linux-g++'
  - '. /opt/qt$QT/bin/qt$QT-env.sh'

script:
  - qmake src/Emu80qt.pro    # Generate Makefile
  - cat ./Makefile
  - make                     # Make
